version: '3.7'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./html:/usr/share/nginx/html"
    networks:
      - app_net
    container_name: "jquery-app-nginx"
  php:
    image: javi98/php-mysqli:fpm
    ports:
      - "9000:9000"
    volumes:
      - "./html:/var/www/html"
    networks:
      - app_net
    container_name: "jquery-app-php"
  mysql:
    image: javi98/mysql-app-jquery:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=calderas
    networks:
      - app_net
    container_name: "jquery-app-mysql"
networks:
  app_net:
    driver: bridge
